# Generated by Django 5.2.15 on 2026-06-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("employees", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(verbose_name="descripcion")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("approved", "Aprobada"),
                            ("closed", "Cerrada"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="employees.employee",
                        verbose_name="asesor",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="clients.client",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="vehicles.vehicle",
                        verbose_name="vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "orden de servicio",
                "verbose_name_plural": "ordenes de servicio",
                "ordering": ["-created_at"],
            },
        ),
    ]
