# Generated by Django 5.2.15 on 2026-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripcion"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
                "ordering": ["name"],
            },
        ),
    ]
