# Generated by Django 5.2.15 on 2026-06-25 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("in_progress", "En progreso"),
                            ("done", "Terminada"),
                            ("delivered", "Entregada"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "interned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de internamiento",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de cierre"
                    ),
                ),
                (
                    "service_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_order",
                        to="sales.serviceorder",
                        verbose_name="orden de servicio",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_orders",
                        to="vehicles.vehicle",
                        verbose_name="vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "orden de trabajo",
                "verbose_name_plural": "ordenes de trabajo",
                "ordering": ["-interned_at"],
            },
        ),
    ]
