# Generated by Django 5.2.15 on 2026-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
        ("vehicles", "0001_initial"),
        ("workshop", "0002_joborder_client_status_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="joborder",
            index=models.Index(
                fields=["status", "interned_at"], name="job_status_date_idx"
            ),
        ),
    ]
