# Generated by Django 5.2.15 on 2026-06-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0002_seed_example_areas"),
        ("employees", "0001_initial"),
        ("teams", "0001_initial"),
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180, verbose_name="titulo")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripcion"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Critica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completada"),
                            ("overdue", "Vencida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="fecha limite")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de finalizacion"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="areas.area",
                        verbose_name="area",
                    ),
                ),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to="employees.employee",
                        verbose_name="empleado responsable",
                    ),
                ),
                (
                    "assigned_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to="teams.team",
                        verbose_name="equipo responsable",
                    ),
                ),
                (
                    "job_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workshop.joborder",
                        verbose_name="orden de trabajo",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="tarea principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea",
                "verbose_name_plural": "tareas",
                "ordering": ["due_date", "priority", "title"],
            },
        ),
    ]
