# Generated by Django 5.2.15 on 2026-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0002_seed_example_areas"),
        ("employees", "0002_employee_user"),
        ("tasks", "0001_initial"),
        ("teams", "0001_initial"),
        ("workshop", "0002_joborder_client_status_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["job_order", "parent_task", "status", "due_date"],
                name="task_board_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "due_date"], name="task_status_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_employee", "status", "due_date"],
                name="task_employee_load_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_team", "status", "due_date"],
                name="task_team_load_idx",
            ),
        ),
    ]
