# Generated by Django 5.2.15 on 2026-06-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140, verbose_name="nombre")),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="areas.area",
                        verbose_name="area",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="employees.employee",
                        verbose_name="integrantes",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "area"), name="unique_team_name_per_area"
                    )
                ],
            },
        ),
    ]
