# Generated by Django 5.2.15 on 2026-06-25 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate", models.CharField(max_length=20, verbose_name="placa")),
                ("make", models.CharField(max_length=80, verbose_name="marca")),
                ("model", models.CharField(max_length=80, verbose_name="modelo")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="anio",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="clients.client",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehiculo",
                "verbose_name_plural": "vehiculos",
                "ordering": ["plate"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plate",), name="unique_vehicle_plate"
                    )
                ],
            },
        ),
    ]
